### ISSUE TITLE
How can I add SVGs into gojs using gojs-react?

### ISSUE THREAD

**Issue by rmGuarachi** [NorthwoodsSoftware/gojs-react#1]
I checked out the tiger example on your website. Is there a way to use SVGs without having to parse the svg file? 

https://github.com/NorthwoodsSoftware/GoJS/blob/master/samples/tiger.html

Thank you

**Comment by simonsarris** [comment]
Please use https://forum.nwoods.com/ for general questions.

You can use SVG as a go.Picture `source`: https://gojs.net/latest/intro/pictures.html#UsingSVGAsPictureSource
