### ISSUE TITLE
Uncaught Error: GraphLinksModel.linkKeyProperty must not be an empty string

### ISSUE THREAD

**Issue by aniot** [NorthwoodsSoftware/gojs-react#5]
ReactDiagram uses Model.mergeLinkDataArray() in componentDidMount and componentDidUpdate.
This method pushes users to make key property in linkDataArray, though most of linkDataArray object has no key property.

**Comment by jonchardy** [comment]
Yes, if you are using a GraphLinksModel, you must provide a linkKeyProperty, as documented in the readme: https://github.com/NorthwoodsSoftware/gojs-react#initdiagraminitpaletteinitoverview
