### ISSUE TITLE
Updating state with different nodeDataArray does not recompute group

### ISSUE THREAD

**Issue by FinPlorer** [NorthwoodsSoftware/gojs-react#6]
Setting a new NodeDataArray with different group create issue.

Ex array :  
```
[{
   key:1
   name:"child",
   category:"child",
   group:2
},
{
   key:2
   name:"group",
   isGroup:true
   category:"group"
}]
```
Then we use setState with :
```
[{
   key:1
   name:"child",
   category:"child",
},
{
   key:2
   name:"group",
   isGroup:true
   category:"group"
}]
```

And the node "child" will still be inside the group.
It seems like those lines are missing from gojs-react :

`       
diagram.startTransaction();
diagram.updateAllRelationshipsFromData();
diagram.updateAllTargetBindings();
diagram.commitTransaction("update");
`

**Comment by jonchardy** [comment]
In your setState call, you need to ensure that 'group' is included if you included it in your state previously.
```
[{
   key:1
   name:"child",
   category:"child",
   group: undefined
},
{
   key:2
   name:"group",
   isGroup:true
   category:"group"
}]
```
GoJS does not make assumptions about what you may want to do with properties that exist in your model and are later removed when merging in data, as we don't want destructive merging.
