### ISSUE TITLE
ReactDiagram update with new links passed from props but ignores change of nodes

### ISSUE THREAD

**Issue by vnenkpet** [NorthwoodsSoftware/gojs-react#7]
When I pass new `props.project.nodes` array, it gets ignored - however new link in `props.project.edges`correctly displays. Is there anything I could be doing wrong? 
Both values are obtained through the same GraphQL query.

```typescript
// Diagram usage

export function ProjectDiagram(props: GetProject) {
  return (
    <div>
      <ReactDiagram
        skipsDiagramUpdate={false}
        initDiagram={initDiagram}
        divClassName="diagram-component"
        nodeDataArray={props.project.nodes.map((node) => ({
          key: node.uniqueName,
          text: node.uniqueName,
        }))}
        linkDataArray={props.project.edges.map((edge) => ({
          key: edge.id,
          from: edge.sourceNodeId,
          to: edge.targetNodeId,
        }))}
        onModelChange={handleModelChange}
      />
    </div>
  );
}
```

```typescript
// GraphQL query which's results are in props

export const GET_PROJECT = gql`
  query GetProject($id: String!) {
    project(id: $id) {
      id
      name
      createdAt
      edges {
        id
        sourceNodeId
        targetNodeId
      }
      nodes {
        uniqueName
      }
      users {
        id
        role
      }
    }
  }
`;
```

**Comment by jonchardy** [comment]
What's the resulting array being passed into ReactDiagram?

**Comment by vnenkpet** [comment]
Initial array:
<img width="540" alt="スクリーンショット 2020-08-11 16 09 15" src="https://user-images.githubusercontent.com/1933654/89907464-02dd2180-dbed-11ea-8aa7-7eea7799a11a.png">

Updated array:
<img width="543" alt="スクリーンショット 2020-08-11 16 09 25" src="https://user-images.githubusercontent.com/1933654/89907481-083a6c00-dbed-11ea-87c4-71d33df84108.png">

Gotten from this console log:
```typescript
// render function...
export function ProjectDiagram(props: GetProject) {
  console.log(props.project.nodes); // HERE
  return (
    <ReactDiagram
      skipsDiagramUpdate={false}
      initDiagram={initDiagram}
      divClassName="diagram-component"
      nodeDataArray={props.project.nodes.map((node) => ({
        key: node.uniqueName,
        text: node.uniqueName,
      }))}
      linkDataArray={props.project.edges.map((edge) => ({
        key: edge.id,
        from: edge.sourceNodeId,
        to: edge.targetNodeId,
      }))}
      onModelChange={handleModelChange}
    />
  );
}

```

The diagram keeps showing only the nodes defined in the first one.

**Comment by jonchardy** [comment]
Hmm, are you sure the ReactDiagram component is receiving the right array? If you put a breakpoint in **ReactDiagram.componentDidUpdate**, what's the value of `this.props.nodeDataArray` on each call?

If you could provide a repo/sandbox for reproduction, that would make it easier to help.

**Comment by vnenkpet** [comment]
I created a minimal repo demonstrating the issue: 

https://github.com/vnenkpet/gojs-minimal-repo-bug/blob/issue/min-repo/app/src/components/ProjectView/ProjectView.tsx

You can see that after clicking on add node, the added edge is properly display (b -> a), bot no node (c) is added.

**Comment by jonchardy** [comment]
The problem is that the node *is* being added to the model, but has no position in the diagram, so it doesn't show up. The links work because their position comes from the related nodes.

You either need to allow your layout to provide a location for new nodes by leaving **isOngoing** and **isRealtime** as their defaults, or your new node data objects need to include a `loc` property.

Commenting out those lines and clicking the button results in a new node as expected.

```ts
  const diagram = $(go.Diagram, {
    "undoManager.isEnabled": true,
    autoScale: go.Diagram.Uniform,
    layout: $(go.ForceDirectedLayout, {
      defaultSpringLength: 40,
      defaultSpringStiffness: 0.05,
      // isOngoing: false,
      // isRealtime: false,
    }),
    model: $(go.GraphLinksModel, {
      linkKeyProperty: "key",
      nodeKeyProperty: "key",
    }),
  });
```

![image](https://user-images.githubusercontent.com/1202288/89916910-2a6cc380-dbc6-11ea-9019-903bafe20442.png)

**Comment by vnenkpet** [comment]
Thanks! That wasn't obvious to me.
