### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'x.navigator.userAgent.indexOf')

### ISSUE THREAD

**Issue by natalyayyad** [NorthwoodsSoftware/gojs-react#8]
I recently installed gojs-react to my react native app, but I keep getting this error:

> TypeError: undefined is not an object (evaluating 'x.navigator.userAgent.indexOf')

Any help on how I can fix this? 
Thanks

**Comment by jonchardy** [comment]
gojs-react is meant to run in the browser and is not designed to be compatible with React Native. Maybe you could get it to work with polyfills or shims, but that would be up to you.
