### ISSUE TITLE
Trying to set undefined property "mode" on object: Diagram

### ISSUE THREAD

**Issue by ghost** [NorthwoodsSoftware/gojs-react#9]
os: linux ubuntu 16.04
node: 15.0.1
gojs: 2.1.31
gojs-react: 1.0.10
react: 17.0.1
webpack: 5.10.0

Trying to start following this project README but getting such error. After removing it, gojs start to complain that GraphLinksModel.linkKeyProperty must be not empty string.

Using modelData from https://gojs.net/latest/samples/flowchart.html

Debugging shows that passing modelData, nodeDataArray and linkDataArray to component not helping at all, linkKeyPropety is empty string same as dataArray.

**Comment by jonchardy** [comment]
Yes, you must set GraphLinksModel.linkKeyProperty when using a GraphLinksModel. Have you seen [gojs-react-basic](https://github.com/NorthwoodsSoftware/gojs-react-basic)?

**Comment by ghost** [comment]
Hi, sorry for delayed answer. Used some code from gojs-react-basic and adjusted styles, now diagram showing up.
